-- NexusStore security hardening migration
-- Run after SUPABASE_SETUP.sql. Safe to rerun. No credentials.
BEGIN;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_chats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payments_select_own ON public.payments;
CREATE POLICY payments_select_own ON public.payments FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = payments.order_id AND (o.user_id = auth.uid() OR public.is_admin())));
DROP POLICY IF EXISTS payments_admin_all ON public.payments;
CREATE POLICY payments_admin_all ON public.payments FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS payment_events_admin_only ON public.payment_events;
CREATE POLICY payment_events_admin_only ON public.payment_events FOR SELECT TO authenticated USING (public.is_admin());
DROP POLICY IF EXISTS coupon_usages_select_own ON public.coupon_usages;
CREATE POLICY coupon_usages_select_own ON public.coupon_usages FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.is_admin());
DROP POLICY IF EXISTS inventory_admin_only ON public.inventory;
CREATE POLICY inventory_admin_only ON public.inventory FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS inventory_movements_admin_only ON public.inventory_movements;
CREATE POLICY inventory_movements_admin_only ON public.inventory_movements FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin() AND admin_id = auth.uid());
DROP POLICY IF EXISTS delivery_chats_select_scoped ON public.delivery_chats;
CREATE POLICY delivery_chats_select_scoped ON public.delivery_chats FOR SELECT TO authenticated USING (public.is_admin() OR EXISTS (SELECT 1 FROM public.deliveries d WHERE d.id = delivery_chats.delivery_id AND d.user_id = auth.uid()));
CREATE OR REPLACE FUNCTION public.protect_profile_security() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN IF auth.uid() = OLD.id AND NOT public.is_admin() THEN NEW.role := OLD.role; NEW.email := OLD.email; END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS trg_protect_profile_security ON public.profiles;
CREATE TRIGGER trg_protect_profile_security BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.protect_profile_security();
DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
DROP POLICY IF EXISTS profiles_admin_update ON public.profiles;
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY profiles_admin_update ON public.profiles FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS orders_update ON public.orders;
DROP POLICY IF EXISTS orders_update_admin_only ON public.orders;
CREATE POLICY orders_update_admin_only ON public.orders FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS coupons_read ON public.coupons;
DROP POLICY IF EXISTS coupons_admin_only ON public.coupons;
CREATE POLICY coupons_admin_only ON public.coupons FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS audit_insert ON public.audit_logs;
DROP POLICY IF EXISTS audit_insert_admin ON public.audit_logs;
CREATE POLICY audit_insert_admin ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (actor_id = auth.uid() AND actor_role = (SELECT role FROM public.profiles WHERE id = auth.uid()));
REVOKE INSERT, UPDATE, DELETE ON public.payments FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.payment_events FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.coupon_usages FROM authenticated;
DO $$ BEGIN ALTER TABLE public.products ADD CONSTRAINT products_price_nonnegative CHECK (price >= 0); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.products ADD CONSTRAINT products_promo_nonnegative CHECK (promo_price IS NULL OR promo_price >= 0); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.payments ADD CONSTRAINT payments_amount_positive CHECK (amount > 0); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS payments_external_id_unique ON public.payments(external_id) WHERE external_id IS NOT NULL;
COMMIT;
